-- Thirty additional longevity topics selected from the expanded Hallmarks of
-- Aging framework, NIA intervention-testing priorities, active translational
-- research, and healthspan outcomes. Queries deliberately require ageing or
-- longevity context so common biomedical terms do not create noisy matches.

insert into public.intelligence_topics
  (slug, name, description, literature_query, trials_query, sort_order)
values
  ('genomic-instability', 'Genomic instability', 'How accumulated DNA damage, chromosome errors, and repair failure contribute to ageing.', '("genomic instability" OR "DNA damage" OR "DNA repair") AND (aging OR ageing OR longevity OR healthspan)', '("genomic instability" OR "DNA damage" OR "DNA repair") AND (aging OR ageing OR longevity)', 130),
  ('telomeres-telomerase', 'Telomeres and telomerase', 'Research on telomere shortening, telomerase, cellular ageing, and possible interventions.', '(telomere* OR telomerase) AND (aging OR ageing OR longevity OR rejuvenation)', '(telomere OR telomerase) AND (aging OR ageing OR longevity)', 140),
  ('epigenetic-alterations', 'Epigenetic alterations', 'Age-related changes in chromatin, DNA methylation, histones, and gene regulation beyond clock measurement.', '("epigenetic alteration" OR chromatin OR histone OR "DNA methylation") AND (aging OR ageing OR longevity OR rejuvenation)', '(epigenetic OR chromatin OR "DNA methylation") AND (aging OR ageing OR longevity)', 150),
  ('proteostasis', 'Proteostasis', 'Protein folding, quality control, aggregation, and clearance as they change with age.', '(proteostasis OR "protein homeostasis" OR "protein aggregation") AND (aging OR ageing OR longevity OR healthspan)', '(proteostasis OR "protein homeostasis" OR "protein aggregation") AND (aging OR ageing)', 160),
  ('autophagy', 'Autophagy', 'Cellular recycling, lysosomal function, and autophagy-related interventions in ageing.', '(autophagy OR macroautophagy OR lysosomal) AND (aging OR ageing OR longevity OR healthspan)', '(autophagy OR macroautophagy OR lysosomal) AND (aging OR ageing OR longevity)', 170),
  ('nutrient-sensing', 'Nutrient sensing', 'How mTOR, AMPK, insulin, IGF-1, and related pathways connect nutrition with ageing.', '("nutrient sensing" OR AMPK OR "IGF-1" OR "insulin signaling") AND (aging OR ageing OR longevity OR healthspan)', '("nutrient sensing" OR AMPK OR "IGF-1" OR "insulin signaling") AND (aging OR ageing OR longevity)', 180),
  ('mitochondrial-function', 'Mitochondrial function', 'Mitochondrial quality, energy production, oxidative stress, and mitophagy in ageing.', '("mitochondrial dysfunction" OR mitophagy OR "mitochondrial function") AND (aging OR ageing OR longevity OR healthspan)', '("mitochondrial dysfunction" OR mitophagy OR "mitochondrial function") AND (aging OR ageing OR longevity)', 190),
  ('intercellular-communication', 'Intercellular communication', 'How endocrine, neuronal, immune, and extracellular signals change between cells and tissues with age.', '("intercellular communication" OR "cell-cell communication" OR "extracellular vesicle") AND (aging OR ageing OR longevity)', '("intercellular communication" OR "extracellular vesicle") AND (aging OR ageing OR longevity)', 200),
  ('chronic-inflammation', 'Chronic inflammation', 'Low-grade age-related inflammation, often called inflammaging, and its health consequences.', '(inflammaging OR inflammageing OR "chronic inflammation") AND (aging OR ageing OR longevity OR healthspan)', '(inflammaging OR inflammageing OR "chronic inflammation") AND (aging OR ageing OR frailty)', 210),
  ('microbiome-dysbiosis', 'Microbiome and dysbiosis', 'Changes in gut and other microbial communities linked with ageing and healthspan.', '(microbiome OR dysbiosis OR "gut microbiota") AND (aging OR ageing OR longevity OR healthspan)', '(microbiome OR dysbiosis OR "gut microbiota") AND (aging OR ageing OR longevity OR frailty)', 220),
  ('nad-metabolism', 'NAD metabolism', 'NAD biology and precursors such as nicotinamide riboside and NMN in ageing research.', '("NAD+" OR "NAD metabolism" OR "nicotinamide riboside" OR "nicotinamide mononucleotide" OR NMN) AND (aging OR ageing OR longevity OR healthspan)', '("nicotinamide riboside" OR "nicotinamide mononucleotide" OR NMN OR "NAD+") AND (aging OR ageing OR longevity)', 230),
  ('sirtuins', 'Sirtuins', 'SIRT-family enzymes, metabolic regulation, stress responses, and longevity biology.', '(sirtuin* OR SIRT1 OR SIRT3 OR SIRT6) AND (aging OR ageing OR longevity OR healthspan)', '(sirtuin OR SIRT1 OR SIRT3 OR SIRT6) AND (aging OR ageing OR longevity)', 240),
  ('spermidine', 'Spermidine', 'Preclinical and human evidence on spermidine, autophagy, cardiovascular ageing, and cognition.', 'spermidine AND (aging OR ageing OR longevity OR healthspan)', 'spermidine AND (aging OR ageing OR longevity OR older adults)', 250),
  ('urolithin-a', 'Urolithin A', 'Research on urolithin A, mitophagy, muscle function, and age-related decline.', '("urolithin A" OR urolithin-A) AND (aging OR ageing OR longevity OR muscle OR healthspan)', '("urolithin A" OR urolithin-A) AND (aging OR ageing OR older adults OR muscle)', 260),
  ('taurine', 'Taurine', 'Evidence on taurine levels, supplementation, ageing biology, and health outcomes.', 'taurine AND (aging OR ageing OR longevity OR healthspan)', 'taurine AND (aging OR ageing OR longevity OR older adults)', 270),
  ('glycine-glynac', 'Glycine and GlyNAC', 'Glycine and glycine-plus-N-acetylcysteine research in ageing, glutathione biology, and metabolic health.', '(glycine OR GlyNAC OR "glycine N-acetylcysteine") AND (aging OR ageing OR longevity OR healthspan)', '(glycine OR GlyNAC OR "glycine N-acetylcysteine") AND (aging OR ageing OR older adults)', 280),
  ('alpha-ketoglutarate', 'Alpha-ketoglutarate', 'Alpha-ketoglutarate metabolism and supplementation in ageing and healthspan research.', '("alpha-ketoglutarate" OR "alpha ketoglutarate" OR AKG) AND (aging OR ageing OR longevity OR healthspan)', '("alpha-ketoglutarate" OR "alpha ketoglutarate" OR AKG) AND (aging OR ageing OR longevity)', 290),
  ('acarbose', 'Acarbose', 'Acarbose research spanning glucose metabolism, lifespan studies, and translation to healthy ageing.', 'acarbose AND (aging OR ageing OR longevity OR lifespan OR healthspan)', 'acarbose AND (aging OR ageing OR longevity OR older adults)', 300),
  ('canagliflozin', 'Canagliflozin and SGLT2', 'SGLT2-inhibitor research connected with ageing, lifespan, frailty, and organ health.', '(canagliflozin OR "SGLT2 inhibitor") AND (aging OR ageing OR longevity OR healthspan OR frailty)', '(canagliflozin OR "SGLT2 inhibitor") AND (aging OR ageing OR longevity OR frailty)', 310),
  ('17alpha-estradiol', '17α-estradiol', 'Preclinical longevity research on the non-feminising steroid 17α-estradiol and sex-specific effects.', '("17alpha-estradiol" OR "17-alpha estradiol" OR "17α-estradiol") AND (aging OR ageing OR longevity OR lifespan)', '("17alpha-estradiol" OR "17-alpha estradiol" OR "17α-estradiol") AND (aging OR ageing OR longevity)', 320),
  ('ketogenic-diets', 'Ketogenic diets', 'Ketogenic dietary patterns, ketone biology, brain health, and ageing-related outcomes.', '("ketogenic diet" OR ketosis OR "ketone body") AND (aging OR ageing OR longevity OR healthspan)', '("ketogenic diet" OR ketosis OR "ketone body") AND (aging OR ageing OR older adults)', 330),
  ('protein-restriction', 'Protein and amino-acid restriction', 'Protein, methionine, and branched-chain amino-acid restriction in ageing research.', '("protein restriction" OR "methionine restriction" OR "amino acid restriction" OR "BCAA restriction") AND (aging OR ageing OR longevity OR healthspan)', '("protein restriction" OR "methionine restriction" OR "amino acid restriction") AND (aging OR ageing OR longevity)', 340),
  ('young-blood-parabiosis', 'Young blood and parabiosis', 'Heterochronic parabiosis, circulating factors, and claims about young plasma, separated from plasma exchange.', '(parabiosis OR "young blood" OR "young plasma" OR "circulating factors") AND (aging OR ageing OR rejuvenation OR longevity)', '(parabiosis OR "young blood" OR "young plasma") AND (aging OR ageing OR rejuvenation)', 350),
  ('heat-cold-hormesis', 'Heat, cold, and hormesis', 'Research on sauna, heat shock, cold exposure, and adaptive stress responses in ageing.', '(hormesis OR sauna OR "heat exposure" OR "cold exposure" OR "heat shock protein") AND (aging OR ageing OR longevity OR healthspan)', '(hormesis OR sauna OR "heat exposure" OR "cold exposure") AND (aging OR ageing OR longevity OR older adults)', 360),
  ('frailty', 'Frailty', 'How frailty is measured, prevented, and treated as a major outcome of biological and clinical ageing.', '(frailty OR "frailty index") AND (aging OR ageing OR longevity OR healthspan OR older adults)', '(frailty OR "frailty index") AND (aging OR ageing OR older adults)', 370),
  ('sarcopenia', 'Sarcopenia', 'Age-related loss of muscle mass, strength, and function, including prevention and treatment research.', '(sarcopenia OR "muscle aging" OR "muscle ageing") AND (aging OR ageing OR longevity OR healthspan)', '(sarcopenia OR "muscle aging" OR "muscle ageing") AND (aging OR ageing OR older adults)', 380),
  ('cognitive-aging', 'Cognitive ageing', 'Changes in memory, thinking, brain resilience, and dementia risk across later life.', '("cognitive aging" OR "cognitive ageing" OR "brain aging" OR "brain ageing") AND (longevity OR healthspan OR older adults OR ageing OR aging)', '("cognitive aging" OR "cognitive ageing" OR "brain aging" OR "brain ageing") AND (older adults OR longevity)', 390),
  ('cardiovascular-aging', 'Cardiovascular ageing', 'Vascular stiffness, cardiac ageing, endothelial function, and cardiovascular healthspan.', '("cardiovascular aging" OR "cardiovascular ageing" OR "vascular aging" OR "vascular ageing" OR "arterial stiffness") AND (longevity OR healthspan OR older adults OR aging OR ageing)', '("cardiovascular aging" OR "vascular aging" OR "arterial stiffness") AND (older adults OR longevity OR healthspan)', 400),
  ('immune-aging', 'Immune ageing', 'Immunosenescence, vaccine responses, immune resilience, and age-related immune dysfunction.', '(immunosenescence OR "immune aging" OR "immune ageing" OR "immune resilience") AND (aging OR ageing OR longevity OR healthspan)', '(immunosenescence OR "immune aging" OR "immune ageing") AND (older adults OR aging OR ageing)', 410),
  ('ovarian-aging', 'Ovarian ageing', 'Reproductive longevity, ovarian reserve, menopause biology, and interventions aimed at ovarian ageing.', '("ovarian aging" OR "ovarian ageing" OR "reproductive longevity" OR "ovarian reserve") AND (aging OR ageing OR longevity OR menopause)', '("ovarian aging" OR "ovarian ageing" OR "reproductive longevity" OR "ovarian reserve") AND (aging OR ageing OR menopause)', 420)
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  literature_query = excluded.literature_query,
  trials_query = excluded.trials_query,
  sort_order = excluded.sort_order,
  enabled = true,
  updated_at = now();

select public.refresh_intelligence_entities();

