-- Forty additional, non-duplicate longevity topics spanning human biomarkers,
-- emerging mechanisms, organ ageing, functional outcomes, and translational
-- geroscience. Every broad term requires explicit ageing or longevity context.

insert into public.intelligence_topics
  (slug, name, description, literature_query, trials_query, sort_order)
values
  ('longevity-genetics', 'Longevity genetics', 'Genes and variants associated with exceptional survival, healthspan, and lifespan.', '("longevity gene" OR "longevity genetics" OR "exceptional longevity" OR "lifespan genetics") AND (aging OR ageing OR longevity OR centenarian)', '("longevity gene" OR "longevity genetics" OR "exceptional longevity") AND (aging OR ageing OR longevity)', 430),
  ('centenarian-biology', 'Centenarian biology', 'Biology, resilience, and health patterns in centenarians and other exceptionally long-lived people.', '(centenarian OR supercentenarian OR "exceptional longevity") AND (biology OR resilience OR healthspan OR genetics)', '(centenarian OR supercentenarian OR "exceptional longevity")', 440),
  ('biological-age-biomarkers', 'Biological age biomarkers', 'Composite measures of biological age beyond any single clock technology.', '("biological age" OR "aging biomarker" OR "ageing biomarker" OR "pace of aging") AND (validation OR mortality OR healthspan)', '("biological age" OR "aging biomarker" OR "ageing biomarker") AND (aging OR ageing OR longevity)', 450),
  ('proteomic-aging', 'Proteomic ageing', 'Protein signatures and proteomic clocks used to study biological ageing and health risk.', '("proteomic aging" OR "proteomic ageing" OR "proteomic clock" OR "protein aging signature")', '("proteomic aging" OR "proteomic ageing" OR "proteomic clock")', 460),
  ('metabolomic-aging', 'Metabolomic ageing', 'Metabolite patterns, metabolic clocks, and small-molecule signatures of ageing.', '("metabolomic aging" OR "metabolomic ageing" OR "metabolomic clock" OR "metabolic age")', '("metabolomic aging" OR "metabolomic ageing" OR "metabolomic clock")', 470),
  ('transcriptomic-aging', 'Transcriptomic ageing', 'Age-related gene-expression signatures and transcriptomic measures of biological age.', '("transcriptomic aging" OR "transcriptomic ageing" OR "transcriptomic clock" OR "gene expression age")', '("transcriptomic aging" OR "transcriptomic ageing" OR "transcriptomic clock")', 480),
  ('single-cell-aging', 'Single-cell ageing', 'Single-cell and spatial studies of how individual cell populations change with age.', '("single-cell aging" OR "single cell aging" OR "single-cell ageing" OR "single cell ageing")', '("single-cell aging" OR "single cell aging" OR "single-cell ageing")', 490),
  ('multi-omics-aging', 'Multi-omics ageing', 'Integrated genomic, epigenomic, proteomic, metabolomic, and clinical views of ageing.', '("multi-omics aging" OR "multiomics aging" OR "multi-omics ageing" OR "multiomic ageing")', '("multi-omics aging" OR "multiomics aging" OR "multi-omics ageing")', 500),
  ('rna-splicing-aging', 'RNA splicing and ageing', 'Splicing regulation, RNA processing, and age-related changes in transcript quality.', '("RNA splicing" OR "alternative splicing" OR spliceosome) AND (aging OR ageing OR longevity OR senescence)', '("RNA splicing" OR "alternative splicing" OR spliceosome) AND (aging OR ageing)', 510),
  ('clonal-hematopoiesis', 'Clonal haematopoiesis', 'Age-related blood-cell clones, CHIP, inflammation, and disease risk.', '("clonal hematopoiesis" OR "clonal haematopoiesis" OR CHIP) AND (aging OR ageing OR age-related OR longevity)', '("clonal hematopoiesis" OR "clonal haematopoiesis" OR CHIP) AND (aging OR ageing OR older adults)', 520),
  ('extracellular-matrix-aging', 'Extracellular matrix ageing', 'How tissue stiffness, fibrosis, matrix turnover, and mechanobiology change with age.', '("extracellular matrix" OR mechanobiology OR "tissue stiffness" OR fibrosis) AND (aging OR ageing OR longevity)', '("extracellular matrix" OR "tissue stiffness" OR fibrosis) AND (aging OR ageing OR older adults)', 530),
  ('glycation-ages', 'Glycation and AGEs', 'Advanced glycation end products, cross-linking, tissue ageing, and related interventions.', '("advanced glycation end product" OR glycation OR "AGE crosslink") AND (aging OR ageing OR longevity OR age-related)', '("advanced glycation end product" OR glycation OR "AGE crosslink") AND (aging OR ageing OR older adults)', 540),
  ('oxidative-stress', 'Oxidative stress', 'Reactive oxygen species, redox balance, antioxidant systems, and ageing biology.', '("oxidative stress" OR "redox homeostasis" OR "reactive oxygen species") AND (aging OR ageing OR longevity OR senescence)', '("oxidative stress" OR "redox homeostasis") AND (aging OR ageing OR older adults)', 550),
  ('ferroptosis-aging', 'Ferroptosis and ageing', 'Iron-dependent cell death, lipid peroxidation, and age-related tissue decline.', '(ferroptosis OR "iron-dependent cell death") AND (aging OR ageing OR longevity OR senescence)', '(ferroptosis OR "iron-dependent cell death") AND (aging OR ageing OR older adults)', 560),
  ('cell-competition', 'Cell competition', 'How tissues remove, retain, or replace less-fit cells during ageing.', '("cell competition" OR "fitness selection") AND (aging OR ageing OR longevity OR senescence)', '("cell competition" OR "fitness selection") AND (aging OR ageing)', 570),
  ('senescence-sasp', 'Senescence-associated secretory phenotype', 'SASP signals, senomorphic strategies, and the tissue effects of senescent cells.', '(SASP OR "senescence-associated secretory phenotype" OR senomorphic) AND (aging OR ageing OR longevity)', '(SASP OR "senescence-associated secretory phenotype" OR senomorphic) AND (aging OR ageing OR older adults)', 580),
  ('thymic-aging', 'Thymic ageing', 'Thymic involution, T-cell production, and attempts to restore immune function with age.', '("thymic aging" OR "thymic ageing" OR "thymic involution" OR "thymic regeneration")', '("thymic aging" OR "thymic ageing" OR "thymic involution" OR "thymic regeneration")', 590),
  ('hematopoietic-stem-cell-aging', 'Blood stem-cell ageing', 'Age-related changes in haematopoietic stem cells and blood-system renewal.', '("hematopoietic stem cell aging" OR "haematopoietic stem cell ageing" OR "aged hematopoietic stem cell")', '("hematopoietic stem cell aging" OR "haematopoietic stem cell ageing")', 600),
  ('neuroinflammation', 'Neuroinflammation', 'Inflammatory signalling in the ageing brain and its links to cognitive decline.', 'neuroinflammation AND (aging OR ageing OR longevity OR "older adults")', 'neuroinflammation AND (aging OR ageing OR "older adults")', 610),
  ('blood-brain-barrier-aging', 'Blood-brain barrier ageing', 'Age-related changes in blood-brain barrier integrity, transport, and neurovascular health.', '("blood-brain barrier" OR neurovascular) AND (aging OR ageing OR longevity OR senescence)', '("blood-brain barrier" OR neurovascular) AND (aging OR ageing OR older adults)', 620),
  ('glymphatic-clearance', 'Glymphatic clearance', 'Brain waste-clearance pathways, sleep, and age-related neurological health.', '(glymphatic OR "brain waste clearance") AND (aging OR ageing OR longevity OR "older adults")', '(glymphatic OR "brain waste clearance") AND (aging OR ageing OR older adults)', 630),
  ('kidney-aging', 'Kidney ageing', 'Renal ageing, declining filtration, fibrosis, and kidney healthspan.', '("kidney aging" OR "kidney ageing" OR "renal aging" OR "renal ageing")', '("kidney aging" OR "kidney ageing" OR "renal aging" OR "renal ageing")', 640),
  ('liver-aging', 'Liver ageing', 'Age-related liver metabolism, regeneration, steatosis, and fibrosis.', '("liver aging" OR "liver ageing" OR "hepatic aging" OR "hepatic ageing")', '("liver aging" OR "liver ageing" OR "hepatic aging" OR "hepatic ageing")', 650),
  ('lung-aging', 'Lung ageing', 'Pulmonary ageing, respiratory reserve, fibrosis, and tissue repair.', '("lung aging" OR "lung ageing" OR "pulmonary aging" OR "pulmonary ageing")', '("lung aging" OR "lung ageing" OR "pulmonary aging" OR "pulmonary ageing")', 660),
  ('skin-aging', 'Skin ageing', 'Skin structure, barrier function, photoageing, wound repair, and regeneration.', '("skin aging" OR "skin ageing" OR photoaging OR photoageing) AND (longevity OR senescence OR regeneration OR age-related)', '("skin aging" OR "skin ageing" OR photoaging OR photoageing) AND (older adults OR ageing OR aging)', 670),
  ('bone-aging', 'Bone ageing', 'Bone loss, osteoporosis, bone quality, and skeletal resilience across later life.', '("bone aging" OR "bone ageing" OR osteoporosis OR "skeletal aging") AND (aging OR ageing OR longevity OR older adults)', '("bone aging" OR "bone ageing" OR osteoporosis OR "skeletal aging") AND (older adults OR aging OR ageing)', 680),
  ('joint-cartilage-aging', 'Joint and cartilage ageing', 'Cartilage degeneration, osteoarthritis, tissue repair, and mobility with age.', '("cartilage aging" OR "cartilage ageing" OR osteoarthritis OR "joint aging") AND (aging OR ageing OR longevity OR older adults)', '("cartilage aging" OR "cartilage ageing" OR osteoarthritis OR "joint aging") AND (older adults OR aging OR ageing)', 690),
  ('vision-aging', 'Vision ageing', 'Retinal, lens, and ocular changes that affect vision in later life.', '("vision aging" OR "vision ageing" OR "retinal aging" OR "ocular aging" OR "age-related macular degeneration")', '("vision aging" OR "vision ageing" OR "retinal aging" OR "age-related macular degeneration")', 700),
  ('hearing-aging', 'Hearing ageing', 'Age-related hearing loss, auditory processing, and sensory resilience.', '("age-related hearing loss" OR presbycusis OR "hearing aging" OR "hearing ageing")', '("age-related hearing loss" OR presbycusis OR "hearing aging" OR "hearing ageing")', 710),
  ('oral-health-aging', 'Oral health and ageing', 'Periodontal health, tooth loss, oral microbiology, and links with healthy ageing.', '("oral health" OR periodontitis OR edentulism) AND (aging OR ageing OR longevity OR older adults)', '("oral health" OR periodontitis OR edentulism) AND (aging OR ageing OR older adults)', 720),
  ('cancer-and-aging', 'Cancer and ageing', 'Shared mechanisms, trade-offs, and treatment questions at the intersection of cancer and ageing.', '(cancer OR tumor OR tumour) AND ("aging biology" OR "ageing biology" OR geroscience OR longevity OR senescence)', '(cancer OR tumor OR tumour) AND (aging OR ageing OR geroscience OR older adults)', 730),
  ('multimorbidity', 'Multimorbidity', 'Coexisting chronic conditions, shared ageing drivers, and whole-person outcomes.', '(multimorbidity OR "multiple chronic conditions") AND (aging OR ageing OR longevity OR healthspan OR older adults)', '(multimorbidity OR "multiple chronic conditions") AND (aging OR ageing OR older adults)', 740),
  ('physiological-resilience', 'Physiological resilience', 'The ability to recover from infection, surgery, stress, and other health challenges with age.', '("physiological resilience" OR "physical resilience" OR "recovery resilience") AND (aging OR ageing OR older adults OR longevity)', '("physiological resilience" OR "physical resilience") AND (aging OR ageing OR older adults)', 750),
  ('circadian-rhythms', 'Circadian rhythms', 'Biological timing, clock disruption, chronobiology, and healthy ageing.', '("circadian rhythm" OR chronobiology OR "circadian clock") AND (aging OR ageing OR longevity OR healthspan)', '("circadian rhythm" OR chronobiology OR "circadian clock") AND (aging OR ageing OR older adults)', 760),
  ('time-restricted-eating', 'Time-restricted eating', 'Meal timing and daily eating windows studied separately from general calorie restriction.', '("time-restricted eating" OR "time restricted feeding" OR "early time-restricted") AND (aging OR ageing OR longevity OR healthspan OR older adults)', '("time-restricted eating" OR "time restricted feeding") AND (aging OR ageing OR older adults)', 770),
  ('mediterranean-diet', 'Mediterranean diet', 'Dietary-pattern research on ageing, function, cognition, and chronic-disease risk.', '("Mediterranean diet" OR "Mediterranean dietary pattern") AND (aging OR ageing OR longevity OR healthspan OR older adults)', '("Mediterranean diet" OR "Mediterranean dietary pattern") AND (aging OR ageing OR older adults)', 780),
  ('resistance-training', 'Resistance training', 'Strength training, muscle function, bone health, and independence in later life.', '("resistance training" OR "strength training") AND (aging OR ageing OR longevity OR healthspan OR older adults)', '("resistance training" OR "strength training") AND (aging OR ageing OR older adults)', 790),
  ('aerobic-fitness', 'Aerobic fitness and VO2 max', 'Cardiorespiratory fitness, VO2 max, endurance, and healthy ageing outcomes.', '("cardiorespiratory fitness" OR "aerobic fitness" OR "VO2 max" OR VO2max) AND (aging OR ageing OR longevity OR healthspan)', '("cardiorespiratory fitness" OR "aerobic fitness" OR "VO2 max" OR VO2max) AND (aging OR ageing OR older adults)', 800),
  ('digital-biomarkers', 'Digital biomarkers', 'Wearables, passive sensing, and digital measures of function, sleep, and biological ageing.', '("digital biomarker" OR wearable OR "passive sensing") AND (aging OR ageing OR longevity OR healthspan OR frailty)', '("digital biomarker" OR wearable OR "passive sensing") AND (aging OR ageing OR older adults OR frailty)', 810),
  ('regenerative-medicine', 'Regenerative medicine', 'Tissue engineering, organoids, biomaterials, and repair strategies for age-related decline.', '("regenerative medicine" OR "tissue engineering" OR organoid OR biomaterial) AND (aging OR ageing OR longevity OR rejuvenation)', '("regenerative medicine" OR "tissue engineering" OR organoid OR biomaterial) AND (aging OR ageing OR older adults)', 820)
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  literature_query = excluded.literature_query,
  trials_query = excluded.trials_query,
  sort_order = excluded.sort_order,
  enabled = true,
  updated_at = now();

select public.refresh_intelligence_entities();

do $$
declare enabled_count integer;
begin
  select count(*) into enabled_count from public.intelligence_topics where enabled;
  if enabled_count < 82 then
    raise exception 'Expected at least 82 enabled longevity topics, found %', enabled_count;
  end if;
end $$;
