CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.members (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  x_id text NOT NULL,
  x_username text NOT NULL,
  x_display_name text NOT NULL,
  x_avatar_url text,
  x_follower_count integer DEFAULT 0 NOT NULL,
  points integer DEFAULT 0 NOT NULL,
  tier text DEFAULT 'member' NOT NULL,
  invited_by bigint,
  referral_chain_depth integer DEFAULT 0 NOT NULL,
  network_size integer DEFAULT 0 NOT NULL,
  multiplier numeric(3,1) DEFAULT 1.0 NOT NULL,
  last_login timestamptz DEFAULT now(),
  last_daily_claim timestamptz,
  login_streak integer DEFAULT 0 NOT NULL,
  confirmed_email boolean DEFAULT false NOT NULL,
  is_og boolean DEFAULT false NOT NULL
);

ALTER TABLE public.members ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE public.members ADD COLUMN IF NOT EXISTS x_id text;
ALTER TABLE public.members ADD COLUMN IF NOT EXISTS x_username text;
ALTER TABLE public.members ADD COLUMN IF NOT EXISTS x_display_name text;
ALTER TABLE public.members ADD COLUMN IF NOT EXISTS x_avatar_url text;
ALTER TABLE public.members ADD COLUMN IF NOT EXISTS x_follower_count integer DEFAULT 0;
ALTER TABLE public.members ADD COLUMN IF NOT EXISTS points integer DEFAULT 0;
ALTER TABLE public.members ADD COLUMN IF NOT EXISTS tier text DEFAULT 'member';
ALTER TABLE public.members ADD COLUMN IF NOT EXISTS invited_by bigint;
ALTER TABLE public.members ADD COLUMN IF NOT EXISTS referral_chain_depth integer DEFAULT 0;
ALTER TABLE public.members ADD COLUMN IF NOT EXISTS network_size integer DEFAULT 0;
ALTER TABLE public.members ADD COLUMN IF NOT EXISTS multiplier numeric(3,1) DEFAULT 1.0;
ALTER TABLE public.members ADD COLUMN IF NOT EXISTS last_login timestamptz DEFAULT now();
ALTER TABLE public.members ADD COLUMN IF NOT EXISTS last_daily_claim timestamptz;
ALTER TABLE public.members ADD COLUMN IF NOT EXISTS login_streak integer DEFAULT 0;
ALTER TABLE public.members ADD COLUMN IF NOT EXISTS confirmed_email boolean DEFAULT false;
ALTER TABLE public.members ADD COLUMN IF NOT EXISTS is_og boolean DEFAULT false;

UPDATE public.members SET x_follower_count = 0 WHERE x_follower_count IS NULL;
UPDATE public.members SET points = 0 WHERE points IS NULL;
UPDATE public.members SET tier = 'member' WHERE tier IS NULL;
UPDATE public.members SET referral_chain_depth = 0 WHERE referral_chain_depth IS NULL;
UPDATE public.members SET network_size = 0 WHERE network_size IS NULL;
UPDATE public.members SET multiplier = 1.0 WHERE multiplier IS NULL;
UPDATE public.members SET login_streak = 0 WHERE login_streak IS NULL;
UPDATE public.members SET confirmed_email = false WHERE confirmed_email IS NULL;
UPDATE public.members SET is_og = false WHERE is_og IS NULL;
UPDATE public.members SET
  x_follower_count = greatest(x_follower_count, 0),
  points = greatest(points, 0),
  referral_chain_depth = greatest(referral_chain_depth, 0),
  network_size = greatest(network_size, 0),
  login_streak = greatest(login_streak, 0);
UPDATE public.members SET multiplier = CASE
  WHEN network_size >= 200 THEN 3.0
  WHEN network_size >= 51 THEN 2.0
  WHEN network_size >= 11 THEN 1.5
  ELSE 1.0
END;

ALTER TABLE public.members ALTER COLUMN x_follower_count SET NOT NULL;
ALTER TABLE public.members ALTER COLUMN points SET NOT NULL;
ALTER TABLE public.members ALTER COLUMN tier SET NOT NULL;
ALTER TABLE public.members ALTER COLUMN referral_chain_depth SET NOT NULL;
ALTER TABLE public.members ALTER COLUMN network_size SET NOT NULL;
ALTER TABLE public.members ALTER COLUMN multiplier SET NOT NULL;
ALTER TABLE public.members ALTER COLUMN login_streak SET NOT NULL;
ALTER TABLE public.members ALTER COLUMN confirmed_email SET NOT NULL;
ALTER TABLE public.members ALTER COLUMN is_og SET NOT NULL;

ALTER TABLE public.members DROP CONSTRAINT IF EXISTS members_nonnegative_values;
ALTER TABLE public.members ADD CONSTRAINT members_nonnegative_values CHECK (
  x_follower_count >= 0 AND points >= 0 AND referral_chain_depth >= 0 AND
  network_size >= 0 AND login_streak >= 0
);
ALTER TABLE public.members DROP CONSTRAINT IF EXISTS members_multiplier_values;
ALTER TABLE public.members ADD CONSTRAINT members_multiplier_values
  CHECK (multiplier IN (1.0, 1.5, 2.0, 3.0));

CREATE UNIQUE INDEX IF NOT EXISTS members_x_id_key ON public.members (x_id);
CREATE INDEX IF NOT EXISTS members_leaderboard_idx ON public.members (points DESC, created_at ASC, id ASC);
CREATE INDEX IF NOT EXISTS members_invited_by_idx ON public.members (invited_by);

ALTER TABLE public.members DROP CONSTRAINT IF EXISTS members_invited_by_fkey;
ALTER TABLE public.members
  ADD CONSTRAINT members_invited_by_fkey
  FOREIGN KEY (invited_by) REFERENCES public.members(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS public.invite_codes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  code text NOT NULL,
  owner_id bigint NOT NULL,
  used_by bigint,
  used_at timestamptz,
  is_used boolean DEFAULT false NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS invite_codes_code_key ON public.invite_codes (upper(code));
CREATE INDEX IF NOT EXISTS invite_codes_owner_id_idx ON public.invite_codes (owner_id);
ALTER TABLE public.invite_codes DROP CONSTRAINT IF EXISTS invite_codes_owner_id_fkey;
ALTER TABLE public.invite_codes DROP CONSTRAINT IF EXISTS invite_codes_used_by_fkey;
ALTER TABLE public.invite_codes
  ADD CONSTRAINT invite_codes_owner_id_fkey
  FOREIGN KEY (owner_id) REFERENCES public.members(id) ON DELETE CASCADE;
ALTER TABLE public.invite_codes
  ADD CONSTRAINT invite_codes_used_by_fkey
  FOREIGN KEY (used_by) REFERENCES public.members(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS public.points_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  member_id bigint NOT NULL,
  action text NOT NULL,
  points integer NOT NULL,
  meta jsonb DEFAULT '{}'::jsonb NOT NULL
);

CREATE INDEX IF NOT EXISTS points_log_member_created_idx ON public.points_log (member_id, created_at DESC);
ALTER TABLE public.points_log DROP CONSTRAINT IF EXISTS points_log_member_id_fkey;
ALTER TABLE public.points_log
  ADD CONSTRAINT points_log_member_id_fkey
  FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS public.x_posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  member_id bigint NOT NULL,
  post_id text NOT NULL,
  signups_driven integer DEFAULT 0 NOT NULL,
  points_awarded integer DEFAULT 0 NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS x_posts_post_id_key ON public.x_posts (post_id);
ALTER TABLE public.x_posts DROP CONSTRAINT IF EXISTS x_posts_member_id_fkey;
ALTER TABLE public.x_posts
  ADD CONSTRAINT x_posts_member_id_fkey
  FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE;

ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invite_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.points_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.x_posts ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.members, public.invite_codes, public.points_log, public.x_posts FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.members, public.invite_codes, public.points_log, public.x_posts TO service_role;

REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM PUBLIC, anon, authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  REVOKE ALL ON TABLES FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  REVOKE USAGE, SELECT ON SEQUENCES FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC, anon, authenticated;
